service: aws-scraper-cost-optimization

plugins:
  - serverless-bundle
  - serverless-iam-roles-per-function

provider:
  name: aws
  region: us-east-1
  profile: matheus-thiago-tcc
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

custom:
  bundle:
    linting: true # Enable linting as a part of the build process
    aliases: # Create an alias to 'import' modules easily with a custom path
      - Utils: src/utils
      - Crawlers: src/crawlers

functions:
  StartCrawl:
    handler: src/functions/startCrawl.main
