service: aws-scraper-cost-optimization

plugins:
  - serverless-bundle
  - serverless-iam-roles-per-function

provider:
  name: aws
  region: us-east-1
  profile: matheus-thiago-tcc
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    QUEUE_URL: !Ref CrawlQueue
    CRAWL_RESULT_BUCKET: !Ref CrawlResultBucket

custom:
  bundle:
    linting: true # Enable linting as a part of the build process
    forceExclude:
      - aws-sdk # Because it has been already  provided by AWS Cloud environment
      - chrome-aws-lambda # Because it'll be provided through a Lambda Layer
    aliases: # Create an alias to 'import' modules easily with a custom path
      - Utils: src/utils
      - Crawlers: src/crawlers
      - Functions: src/functions

functions:
  - ${file(sls/functions/startCrawl.yml)}
  # Scripts
  - ${file(sls/functions/scripts/populateQueue.yml)}
  - ${file(sls/functions/scripts/consumeQueue.yml)}

resources:
  # S3
  - ${file(sls/resources/s3/crawlResultBucket.yml)}
  # EC2
  - ${file(sls/resources/ec2/scraperSecurityGroup.yml)}
  - ${file(sls/resources/ec2/scraperInstance.yml)}
  # SQS
  - ${file(sls/resources/sqs/crawlQueue.yml)}
