service: aws-scraper-cost-optimization

plugins:
  - serverless-bundle
  - serverless-iam-roles-per-function

provider:
  name: aws
  region: us-east-1
  profile: matheus-thiago-tcc
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
