service: aws-scraper-cost-optimization

plugins:
  - serverless-bundle
  - serverless-iam-roles-per-function

provider:
  name: aws
  region: us-east-1
  profile: matheus-thiago-tcc
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

custom:
  bundle:
    linting: true # Enable linting as a part of the build process
    forceExclude:
      - chrome-aws-lambda # Because it'll be provided through a Lambda Layer
    aliases: # Create an alias to 'import' modules easily with a custom path
      - Utils: src/utils
      - Crawlers: src/crawlers

functions:
  StartCrawl:
    handler: src/functions/startCrawl.main
    memorySize: 1536
    timeout: 30
    # Using a public chrome-aws-lambda layer available at https://github.com/shelfio/chrome-aws-lambda-layer by shelfio
    layers:
      - arn:aws:lambda:${self:provider.region}:764866452798:layer:chrome-aws-lambda:25
