Resources:
  ScrapingQueue:
    Type: AWS::SQS::Queue
    Properties: 
      FifoQueue: true
      QueueName: ${self:service}-scraping-queue.fifo # must end with .fifo suffix
      VisibilityTimeout: 600 # 10 minutes
      ContentBasedDeduplication: false