Resources:
  ScraperInstance:
    Type: AWS::EC2::Instance
    DependsOn:
      - ScraperSecurityGroup
    Properties: 
      CreditSpecification: 
        CPUCredits: unlimited
      ImageId: !GetAtt AmazonLinux2ForScraping.ImageId
      InstanceInitiatedShutdownBehavior: stop
      InstanceType: t3.micro
      KeyName: scraper-instance-key-pair # Key pair created at the AWS Console, because it's not supported by AWS Cloudformation
      Monitoring: true
      SecurityGroupIds:
        - !Ref ScraperSecurityGroup